title: 芜湖！起飞！
author: Aaron丶杨
email: 119010382@link.cuhk.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  AaronYANG
  记着玩玩哇
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

